name: Doctl Test

on:
  push:
    paths:
      - .github/workflows/doctl_test.yml
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.C3P_ENGINE }}
      MINIO_S3_ENDPOINT: ${{ secrets.MINIO_S3_ENDPOINT }}
      MINIO_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY_ID }}
      MINIO_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_ACCESS_KEY }}
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PAT }}

      - name: Compute info and add to firewall
        id: firewall
        run: |
          IP=$(curl https://api.ipify.org)
          FIREWALL=$(doctl compute firewall ls -o json | jq -r '.[] | select(.name == "edm-firewall") | .id')
          RULE="protocol:tcp,ports:all,address:$IP"
          doctl compute firewall add-rules $FIREWALL --inbound-rules $RULE
          echo "::set-output name=FIREWALL::$FIREWALL"
          echo "::set-output name=rule::$RULE"
 
          
      - name: run things
        run: | 
          psql $BUILD_ENGINE -c "SELECT 'this is working' as work;"

      - name: Remove IP from firewall
        env:
          FIREWALL: ${{ steps.firewall.outputs.firewall }}
          RULE: ${{ steps.firewall.outputs.rule }}
        run: |
          doctl compute firewall remove-rules $FIREWALL --inbound-rules $RULE
