name: Doctl Test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.C3P_ENGINE }}
      MINIO_S3_ENDPOINT: ${{ secrets.MINIO_S3_ENDPOINT }}
      MINIO_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY_ID }}
      MINIO_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_ACCESS_KEY }}
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PAT }}

      - name: Compute info and add to firewall
        id: firewall
        run: |
          IP=$(curl https://api.ipify.org)
          FIREWALL=$(doctl compute firewall ls -o json | jq -r '.[] | select(.name == "edm-firewall") | .id')
          RULE="protocol:tcp,ports:5432-5433,address:$IP"
          doctl compute firewall add-rules $FIREWALL --inbound-rules $RULE
          echo "::set-output name=FIREWALL::$FIREWALL"
          echo "::set-output name=rule::$RULE"
 
          
      - name: run things
        run: | 
          psql $BUILD_ENGINE -c "DROP TABLE IF EXISTS doctl_test;"
          psql $BUIL_ENGINE -c "CREATE TABLE doctl_test (
                bbl text,
                field text,
                old_value text,
                new_value text,
            );"

          psql $RECIPE_ENGINE -c "DROP TABLE IF EXISTS test.doctl_test;"
          psql $RECIPE_ENGINE -c "CREATE TABLE test (
                bbl text,
                field text,
                old_value text,
                new_value text,
            );"

      - name: Remove IP from firewall
        env:
          FIREWALL: ${{ steps.firewall.outputs.firewall }}
          RULE: ${{ steps.firewall.outputs.rule }}
        run: |
          doctl compute firewall remove-rules $FIREWALL --inbound-rules $RULE
