name: capital spending cron

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
    scrape:
        runs-on: self-hosted
        container: sptkl/cook:latest
        env:
            RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
            BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
        steps:
          - uses: actions/checkout@v2
          - name: run
            working-directory: capitalprojects_build
            run: |
              pip3 install pathlib requests lxml
              ./11_spending.sh

