name: capital spending

on:
    push:
        branches:
          - refactor-capital-spending
    workflow_dispatch:

jobs:
    scrape:
        timeout-minutes: 720
        runs-on: ubuntu-20.04
        services:
            postgres:
                image: postgis/postgis:12-3.0-alpine
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        env:
            BUILD_ENGINE: postgresql://postgres:postgres@localhost:5432/postgres
            AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
            AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
            AWS_S3_BUCKET: edm-recipes
        steps:
            - uses: actions/checkout@v2

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@master
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                service_account_key: ${{ secrets.GCP_SA_KEY }}
                export_default_credentials: true
            
            - name: Copy the Latest fisa capital commitment to biquery
              working-directory: capitalprojects_build
              run: ./11_spending.sh

            - name: Archive to Data Library -- pgdump
              working-directory: capitalprojects_build
              run:
                docker run --rm \
                    -e AWS_S3_ENDPOINT=$AWS_S3_ENDPOINT\
                    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID\
                    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY\
                    -e AWS_S3_BUCKET=$AWS_S3_BUCKET\
                    -v $(pwd)/templates:/templates\
                    -v $(pwd)/.output:/.output\
                    nycplanning/library:ubuntu-01d9e5eddf65dbdea3eb0c500314963b5ec6246a library archive -f /templates/cpdb_capital_spending.yml -s -l -o pgdump --compress
          
            - name: Archive to Data Library -- csv
              working-directory: capitalprojects_build
              run:
                docker run --rm \
                    -e AWS_S3_ENDPOINT=$AWS_S3_ENDPOINT\
                    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID\
                    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY\
                    -e AWS_S3_BUCKET=$AWS_S3_BUCKET\
                    -v $(pwd)/templates:/templates\
                    -v $(pwd)/.output:/.output\
                    nycplanning/library:ubuntu-01d9e5eddf65dbdea3eb0c500314963b5ec6246a library archive -f /templates/cpdb_capital_spending.yml -s -l -o csv --compress